# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20170330_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subs_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('runs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Runs')),
            ],
        ),
    ]
