# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_subs_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subs_code',
            old_name='runs',
            new_name='run',
        ),
    ]
