# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20170330_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='tid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
