# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20170330_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='submittime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
