# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0006_auto_20170331_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runs',
            name='tid',
        ),
        migrations.AddField(
            model_name='runs',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
