# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0007_auto_20170401_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
