# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_auto_20170401_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problems')),
            ],
        ),
    ]
