# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_test_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
