# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_runs_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
