# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170401_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_id',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
