# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='dateofbirth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='joinDate',
            new_name='join_date',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='profileimage',
            new_name='profile_image',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='totalscore',
            new_name='total_score',
        ),
    ]
